# Generated by Django 4.1.1 on 2023-02-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='excel_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='excel')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
