# Generated by Django 4.1.1 on 2023-02-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0003_excel_files_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel_files',
            name='excel_file',
            field=models.FileField(upload_to='excel'),
        ),
    ]
